export const AeonItem = [
    {
        id: 1,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 2,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 3,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      }, {
        id: 4,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 5,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 6,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 7,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 8,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 9,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 10,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      }
]