export const characterlist = [
  {
    id: 1,
    name: "Viper Ning",
    icon: "/characters/Viper.png",
    image: "/characters/full/viper-ning.webp",
    width: 400,
    height: 600,
    description: `The Blind Blademaster of West Yushan, Viper's very blood has long been suffused with lethal poison. She stands atop the precipice of all mankind,
her blade ever at the ready. As beautiful as she is deadly, her eyes shall never behold this world until the time of destiny is nigh.`,
  },
  {
    id: 2,
    name: "Feria Shen",
    width: 600,
    height: 600,
    icon: "/characters/Feria.png",
    image: "/characters/full/feria-shen.png",
    description: `Feria has always had a defiant streak. Born into a family famed for swordsmithing, the young girl instead grew up obsessed with guns and explosives. Now an adult, she loves nothing more than breaking rules and causing trouble (especially when that means blowing something up). Try and stop her, and you'll be her next victim!`,
  },
  {
    id: 3,
    name: "Tianhai",
    width: 400,
    height: 600,
    icon: "/characters/Tianhai.png",
    description: `Tianhai's travels around the world led him to discover his true calling: to save the world at any cost. This humble monk transforms into a colossal Vajra warrior, spurned by unbridled fury. All those who stand in its path shall feel.`,
  },
  {
    id: 4,
    name: "Ziping Yin",
    icon: "/characters/Ziping.png",
    width: 500,
    height: 600,
    image: "/characters/full/ziping-yin.webp",

    description: `Gifted and selfless, she gives her all in healing and treating anyone in need. Such is her medical skill that you'd be forgiven for thinking just her presence alone can heal the sick or return the fallen from their eternal slumber.`,
  },
  {
    id: 5,
    name: "Temulch",
    width: 400,
    height: 600,
    icon: "/characters/Temulch.png",
    description: `The grassland shall be wracked by furious gales the day that awakens his inner power. His ancestral legends are burned into his mind, and the glory he seeks is so near he can almost taste it. The Grey Wolf shall strike again.`,
  },
  {
    id: 6,
    name: "Tarka Ji",
    width: 400,
    height: 600,
    icon: "/characters/Tarka Ji.png",
    description: `Live fast, drink well, and be merry. Behind the name of the Loyal Drunk stands a man with a love for freedom. His indomitable spirit lends him strength in the face of adversity. The road ahead is fraught with hardship, but no matter how challenging, he'll gladly face it with a sword in hand.`,
  },
  {
    id: 7,
    name: "Tsuchimikado Kurumi",
    icon: "/characters/Kurumi.png",
    image: "/characters/full/kurumi.webp",
    width: 400,
    height: 600,
    description: `Kurumi, known as the Flower of Helioth, is naturally gifted and from an ancient line of Onmyoji masters. Kurumi embarked on the adventure of a lifetime.`,
  },
  {
    id: 8,
    name: "Yoto Hime",
    icon: "/character/Yoto-s.png",
    width: 500,
    height: 600,
    image: "/characters/full/yoto-hime.webp",
    description: `When danger strikes, I transform... Transform into a weapon. That demonic blade. Terrifying, is it not? That's power for you: it strikes a fear deep down inside. Sometimes great strength is no good thing at all. It is a burden that must be carried and controlled.`,
  },
  {
    id: 9,
    name: "Valda Cui",
    icon: "/characters/Valda.png",
    width: 400,
    height: 600,
    image: "/characters/full/valda-cui.webp",
    description: `Valda Cui, a descendant of a general, sighed at the way fate had unfolded as she headed abroad. Yet she harbored great ambition, her mind full of plans and ideas. A remarkable woman skilled at debating and using those around her, she's a most talented figure that fights for the justice she holds dear. What's more, she's a dominant force in all four seas and is sure to make some serious waves.`,
  },
  {
    id: 10,
    name: "Yueshan",
    icon: "/characters/Yueshan.png",
    image: "/characters/full/yueshan.webp",
    width: 400,
    height: 600,
    description: `Gazing ahead at Centralis, with the memories of our march last year still fresh in my mind. The mountains and seas peaceful and clear, laughter hanging in the air. Great waves assail Ridgeshore, and CloudSparrow stretches like a blade into the northern deserts. As the enemy approaches our garrisons from all four corners and the winds soar high, the general will rise to defend the kingdom.`,
  },
  {
    id: 11,
    name: "Wuchen",
    icon: "/characters/Wuchen.png",
    image: "/characters/full/wuchen.webp",
    width: 500,
    height: 600,
    description: `Practice impermanence, and know when to act. Though his blood may be 'impure', his energies somewhat incomplete, Wuchen still provided his ability and rose to become the Herald's secret envoy. He believes that one can reach complete understanding and become an Elucidae if only we cast off the rules that bind us.`,
  },
  {
    id: 12,
    name: "Justina Gu",
    icon: "/character/Justina.png",
    image: "/characters/full/justina-gu.webp",
    width: 400,
    height: 600,
    description: `Encompassed in an icy mist, she comes and goes, fending off blows. In Justina Gu's mind, she is not the noble imperial princess, nor the graceful owner of the Pluvial Pavilion. She is the Frosty Shadow who vows to bury those memories in the snow of the lonely Winter Grace who is eager to find her family back.`,
    skills: [
      { id: 1, name: "Winter's Grace", icon: "/skills/Justina_skill1.png" },
      { id: 2, name: "Frosty Shadow", icon: "/skills/Justina_skill2.png" },
      { id: 3, name: "Frozen Feast", icon: "/skills/Justina_skill3.png" },
    ],
  },
  {
    id: 13,
    name: "Takeda Nobutada",
    icon: "/characters/Takeda.png",
    image: "/characters/full/takeda-nobutada.webp",
    width: 400,
    height: 600,
    description: `Live a life free of desire, with no regrets left behind. Even if spurned by others and accused of injustice, we must still stand by our friends and never break their trust. If faced with a dead end, raise your blade and cut out a new path! Though my body may one day stumble and fall, never shall I forsake my honor!`,
  },
  {
    id: 14,
    name: "Matari",
    icon: "/characters/Matari.png",
    image: "/characters/full/matari.png",
    width: 500,
    height: 600,
    description: `Her skills honed by the desert storms, Matari is as swift as a falcon. Reaching new heights by mastering ancient secret art, she now roams the ruins like a phantom devil.`,
  },
  {
    id: 15,
    name: "Akos Hu",
    icon: "/characters/Akos Hu.png",
    image: "/characters/full/akos-hu.png",
    width: 400,
    height: 600,
    description: `Rough, rude, and reckless, Akos was born free and raised by tigers. Never comfortable within the rigid confines of civilization, he served a brief stint in the military before deserting and throwing himself into the fight against the Empire's injustices. With the people of CloudSparrow behind him and his beloved Feria at his side, he plans to burn the old world down and build a new one from the ashes!`,
  },
  {
    id: 16,
    name: "Zai",
    icon: "/characters/Zai.png",
    image: "/characters/full/zai-ji.png",
    width: 400,
    height: 600,
    description: `Zai's life is defined by pain and struggle. After a prophecy warned she would bring about great calamity, her parents sold her to human traffickers. She spent years in their hands before escaping to the Annica, an elite clan of assassins who recognized her potential for darkness and violence. They trained her to be the ultimate killing machine, and though she was denied the vengeance she initially wanted, she's found the next best thing: destroying everything good and pure in the world.`,
  },
  {
    id: 17,
    name: "Tessa",
    icon: "/characters/Tessa.png",
    width: 600,
    height: 600,
    image: "/characters/full/tessa.webp",
    description: `A young Herald sharing her soul with an ancient fox spirit, Tessa uses charm and trickery to manipulate any and all into doing her bidding. She wields sensuality and wit like weapons, weaving a web of pleasure to ensnare her prey. Though her love might feel genuine, the targets of her affection are little more than pawns in her quest to revive the fallen god Sunwing.`,
  },
  {
    id: 18,
    name: "Hadi Ismail",
    icon: "/characters/Hadi.png",
    image: "/characters/full/Hadi.png",
    width: 500,
    height: 600,
    description: `Hadi refused to yield to adversity. Tragedy and misfortune, instead of breaking him, steeled his determination to shape his own destiny. His unwavering commitment to pursuing knowledge and self-improvement was the path he followed to hold fast to his fate.`,
  },
  {
    id: 19,
    name: "Shayol Wei",
    icon: "/characters/Shayol.png",
    image: "/characters/full/shayol.png",
    width: 600,
    height: 600,
    description: `After becoming a Golden Keeper at a young age, Shayol's status as a prodigy was cemented by her gift for investigation and sound judgment. Sent to the south, she tracked a shadowy conspiracy across hundreds of leagues. Shayol Wei, Chief of the Golden Keepers, will ensure that truth always comes to light.`,
  },
  {
    id: 20,
    name: "Lyam Liu",
    icon: "/characters/Lyam Liu.png",
    image: "/characters/full/lyam-liu.png",
    width: 600,
    height: 600,
    description: `The century-old furnace in Northwestern Fortuna has forged numerous gold and stones, also fostering the metal power passed down through generations of the Liu family. Lyam Liu never believes in natural talent; he knows that only a hard, relentless struggle will see him reach his destination. The ultimate treasure he seeks lies within him, where burning ambition smolders like fire and will illuminate a new path.`,
  },
  {
    id: 21,
    name: "Kylin Zhang",
    icon: "/characters/Kylin.png",
    image: "/characters/full/Kylin1.png",
    width: 600,
    height: 600,
    description: `The patriarch of the Zhang Family, and the keeper of immortality, who holds the transcendent power of the great creature Qilin. To fulfill his family's destiny, Kylin Zhang ventures across the world in search of the lost memories.`,
  },
];
