export const treasures = [
  {
    id: 1,
    name: "Aeon Treasure",
    quantity: 0,
    image: "/treasure/Aeon.png",
    fullImage: "/treasure/full/Aeon-full.png", // Add fullImage here
    items: [
      {
        id: 1,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/1.png",
        owned: true,
      },
      {
        id: 2,
        name: "Test",
        type: "Outfit",
        rarity: "Legendary",
        image: "/treasure/aeon/2.png",
        owned: true,
      },
    ],
  },
  {
    id: 2,
    name: "Brocade treasure",
    quantity: 0,
    image: "/treasure/Brocade.png",
    fullImage: "/placeholder.svg?height=600&width=800", // Add fullImage here
    items: [],
  },
  {
    id: 3,
    name: "Echelon Chest",
    quantity: 24,
    image: "/treasure/Echelon.png",
    fullImage: "/placeholder.svg?height=600&width=800", // Add fullImage here
    items: [
      {
        id: 1,
        name: "Glacial Cascade",
        type: "Outfit",
        description: `The icy blasts focused upon it, in tandem with much medicinal salve, meant that the wound which was left during a big fire when Justina Gu's
childhood, is now completely healed. Justina Gu unwrapped the bandage around her arm, put on the thin gauze skirt, and get ready to bid
farewell to the secretive days of more than ten years.`,
        exclusiveTo: `Justina Gu`,
        rarity: "Extreme",
        image: "/treasure/echelon/1.png",
        owned: true,
      },
      {
        id: 2,
        name: "Kitsune Edge",
        type: "Weapon - Katana",
        description: `Kurumi was always fond of foxes for reasons not even known to herself.
When she made up her mind to make her way to Morus Isle, she had all the great artisans in Cetucraft this word for her.
`,
        rarity: "Extreme",
        image: "/treasure/echelon/2.png",
        owned: false,
      },
      {
        id: 3,
        name: "Huaxia Armors Epoch Glory",
        type: "Outfit",
        description: `Peace falls upon the land, the four tribe safe and protected. A certain contentment flows within the kingdom, never to dry up`,
        exclusiveTo: `Yueshan`,
        rarity: "Legendary",
        image: "/treasure/echelon/3.png",
        owned: true,
      },
      {
        id: 4,
        name: "Hongchuan Maiden",
        type: "Outfit",
        description: `Viper Ning was born on the night of a flare in Yin energy. The skies above the Yushan mountains took on a deep crimson hue,
like a dye that seeped into all the stars above. It's said that this is partly why some know of her as the 'Moonbane Control'.
`,
        exclusiveTo: `Viper Ning`,
        rarity: "Legendary",
        image: "/treasure/echelon/4.png",
        owned: false,
      },
      {
        id: 5,
        name: "Snakevin Spear",
        type: "Weapon - Spear",
        rarity: "Legendary",
        description: `In the records of the Yushan Whisperers, there is a tale of a large snake dressed in purple with a crown of red. They who lay their eyes
upon it are sure to become great leaders and dominate the world.

A Yushan worshiper named Feng Meng would later wield a purple snake staff as he fought off against the forces of five
aristocratic families, never once losing the upper hand. Legend has it that it was no mere staff he wielded, but that
very snake itself.`,
        image: "/treasure/echelon/5.png",
        owned: true,
      },
      {
        id: 6,
        name: "Frostbite",
        type: "Weapon - Nunchuks",
        description: `"So cold..."
Justina dropped the ice formed nunchuks to the ground, clutching hand red-raw from the chill to her pallid neck in an attempt
to the ground, clutching hands red-raw from the chill to her pallid neck in an attempt to warm them just a little.
"Do as I say and channel the pureset energiest of cold. Grow colder than even ice itself, and even frostbite can't harm you!"
The graceful figure of a lady with pale features and immaculately-styled hair stood calmly before her. She crouched down,
picked up the nunchuks, and handed them back to Justina.`,
        rarity: "Legendary",
        image: "/treasure/echelon/6.png",
        owned: false,
      },
      {
        id: 7,
        name: "[Highlights] Billowing Smoke",
        type: "Hair",
        exclusiveTo: "Tarka Ji",
        rarity: "Legendary",
        image: "/treasure/echelon/7.png",
        owned: true,
      },
      {
        id: 8,
        name: "[Highlights] Rosy Clouds",
        type: "Hair",
        exclusiveTo: "Viper Ning",
        rarity: "Legendary",
        image: "/treasure/echelon/8.png",
        owned: false,
      },
      {
        id: 9,
        name: "Dream Catcher",
        type: "Accessory",
        exclusiveTo: "Justina Gu Exclusive",
        description: `As night fell, Granny Aparma helped the Young Justina prepare her last dose of medication. She laid a gentle hand upon
Justina's head, and with a tinge of concern in her voice said "This Dream Catcher will hang above your bed, and with the
moon, it'll protect you as you sleep. It keeps nightmares in the depths of night, so we can live out our good dreams tomorrow."
Justina took that same Dream Catcher with her when she left Lunazra, although she'd long been frfee of her constant nightmares.
She knew that it was not the Dream Catcher's protection that had guarded over her each night, but the tender love of
her mother and Granny Aparma.`,
        rarity: "Legendary",
        image: "/treasure/echelon/9.png",
        owned: false,
      },
      {
        id: 10,
        name: "[Fireworks]",
        type: "Banner",
        exclusiveTo: "Yoto Hime",
        rarity: "Legendary",
        image: "/treasure/echelon/10.png",
        owned: false,
      },
      {
        id: 11,
        name: "[Dragon Insignia Lamp]",
        type: "Banner",
        exclusiveTo: "Tianhai",
        rarity: "Legendary",
        image: "/treasure/echelon/11.png",
        owned: false,
      },
      {
        id: 12,
        name: "Alchemist Apparel Realization",
        type: "Outfit",
        exclusiveTo: "Wu Chen",
        rarity: "Epic",
        image: "/treasure/echelon/12.png",
        owned: false,
      },
      {
        id: 13,
        name: "Hunter Moonlit",
        type: "Outfit",
        exclusiveTo: "Temulch",
        rarity: "Epic",
        image: "/treasure/echelon/13.png",
        owned: false,
      },
      {
        id: 14,
        name: "Winter Silk",
        type: "Outfit",
        exclusiveTo: "Justina Gu",
        rarity: "Epic",
        image: "/treasure/echelon/14.png",
        owned: false,
      },
      {
        id: 15,
        name: "Leaning Heaven Inkwell of Divine",
        type: "Weapon - Longsword",
        rarity: "Epic",
        image: "/treasure/echelon/15.png",
        owned: false,
      },
      {
        id: 16,
        name: "God's Laughter Golden Vengeance",
        type: "Weapon - Gunner",
        rarity: "Epic",
        image: "/treasure/echelon/16.png",
        owned: false,
      },
      {
        id: 17,
        name: "Wildfire",
        type: "Banner",
        rarity: "Epic",
        image: "/treasure/echelon/17.png",
        owned: false,
      },
      {
        id: 18,
        name: "Blush Rabbit",
        type: "Accessory",
        exclusiveTo: "Justina Gu",
        rarity: "Epic",
        image: "/treasure/echelon/18.png",
        owned: false,
      },
      {
        id: 19,
        name: "Hexagram Hat",
        type: "Accessory",
        exclusiveTo: "Wu Chen",
        rarity: "Epic",
        image: "/treasure/echelon/19.png",
        owned: false,
      },
      {
        id: 20,
        name: "Cirrus Shot",
        type: "Accessory",
        exclusiveTo: "Valda Cui",
        rarity: "Epic",
        image: "/treasure/echelon/20.png",
        owned: false,
      },
      {
        id: 21,
        name: "Valda Cui Dear Sister",
        type: "Sticker",
        rarity: "Epic",
        image: "/treasure/echelon/21.png",
        owned: false,
      },
      {
        id: 22,
        name: "Tianhai Prayer",
        type: "Sticker",
        rarity: "Epic",
        image: "/treasure/echelon/22.png",
        owned: false,
      },
      {
        id: 23,
        name: "Unorthodox",
        type: "Idle Style",
        exclusiveTo: "Matari",
        rarity: "Epic",
        image: "/treasure/echelon/23.png",
        owned: false,
      },
      {
        id: 24,
        name: "Destroy",
        type: "Idle Style",
        exclusiveTo: "Yoto Hime",
        rarity: "Epic",
        image: "/treasure/echelon/24.png",
        owned: false,
      },
      {
        id: 25,
        name: "Stardial",
        type: "Banner",
        exclusiveTo: "Wu Chen",
        rarity: "Epic",
        image: "/treasure/echelon/25.png",
        owned: false,
      },
      {
        id: 26,
        name: "Wolf Tomb",
        type: "Banner",
        exclusiveTo: "Temulch",
        rarity: "Epic",
        image: "/treasure/echelon/26.png",
        owned: false,
      },
      {
        id: 27,
        name: "Smoke",
        type: "Banner",
        rarity: "Epic",
        image: "/treasure/echelon/27.png",
        owned: false,
      },
    ],
  },
  {
    id: 4,
    name: "Lotus Treasure",
    quantity: 0,
    image: "/treasure/Lotus.png",
    fullImage: "/placeholder.svg?height=600&width=800", // Add fullImage here
    items: [],
  },
  {
    id: 5,
    name: "Immortal Treasure",
    quantity: 0,
    image: "/treasure/Immortal.png",
    fullImage: "/placeholder.svg?height=600&width=800", // Add fullImage here
    items: [],
  },
];
